### ISSUE TITLE
GLB Preserve material mapping is not working properly

### ISSUE THREAD

**Issue by FrantzVZ777** [playcanvas/editor#202]
I have a complex car model made of 71 materials just for the exterior.
I have attributed materials on the json file in the past. and now need to overwrite the source FBX file in order to generate a GLB file. It seems the GLB is only trying to match the the materials specified on the FBX file.

Here below is the 
<img width="473" alt="Screenshot 2020-10-30 at 11 34 13 AM" src="https://user-images.githubusercontent.com/25144112/97657048-e2ae5780-1aa3-11eb-89c4-463bae981000.png">

If the materials names are correctly matching the source FBX, then the mapping is working.

However i have made slight changes to the material names and attributed the materials differently on the json file.
**PROBLEM: when the GLB is generated it not remember the material mapping made on the JSON.**

See below the GLB created new materials (i purposely set in green to highlight):
<img width="1016" alt="Screenshot 2020-10-30 at 11 31 34 AM" src="https://user-images.githubusercontent.com/25144112/97656904-89debf00-1aa3-11eb-82bb-a3c540e86718.png">

Here below is the JSON file with existing material mapping:
<img width="1027" alt="Screenshot 2020-10-30 at 11 31 53 AM" src="https://user-images.githubusercontent.com/25144112/97656974-b5fa4000-1aa3-11eb-97e2-9e1e839b8ef1.png">

I guess it should not be very difficult to re-link the existing materials to correct mesh instances nodes IDs on the GLB since the json already has the mapping done.,

This is really important to have, because when you have a complex model made of hundreds of material it is very time consuming to go one by one and re-do the mapping (without making mistakes)

**Comment by yaustar** [comment]
> It seems the GLB is only trying to match the the materials specified on the FBX file.

**Comment by FrantzVZ777** [comment]
It would be nice to add an extra option (preserve material mapping from json file)

**Comment by yaustar** [comment]
The issue that during the conversion process, there's no relationship of the JSON from the FBX file. It just converts FBX to GLB.

I reopened the issue as there could be some custom editor code that can be ran in the console to copy the material order and reapply them to the GLB assuming the nodes are in the same order.

**Comment by FrantzVZ777** [comment]
That would be nice to have for the time being...

For longer term, some extra option could be integrated here as mentioned above.
<img width="370" alt="Screenshot 2020-10-30 at 4 14 13 PM" src="https://user-images.githubusercontent.com/25144112/97676041-fae59d00-1aca-11eb-9549-05253c3145c6.png">
preserve material mapping from json file

**Comment by yaustar** [comment]
@slimbuck Did we fix this? 😅

**Comment by yaustar** [comment]
@vkalpias Was this fixed by you?

**Comment by willeastcott** [comment]
Hi @FrantzVZ777. I'm currently trying to clean up the Editor's issue list. This issue is obviously very old and it's not clear whether it was ever resolved. What's your understanding on the current state of this?

**Comment by FrantzVZ777** [comment]
Hi @willeastcott the material mapping is still not working as expected a little bit clunky, many times when i update a 3D model and overwrite it back into the project the materials are duplicated. It is quite random, sometimes it works and sometimes it doesn't I will try to find and example to show you.
