### ISSUE TITLE
Editor warnings and undefined vars

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#88]
When created a new project, the console shows following warnings in the editor tab:

![image](https://user-images.githubusercontent.com/5677782/83354403-0fc5d500-a361-11ea-9176-020c531f51e1.png)

**Comment by willeastcott** [comment]
These are completely harmless and you can ignore them. But yes, to be honest, I don't think there's a justification to print them so I've labelled this as a legitimate bug.

**Comment by Maksims** [comment]
I've added those warnings, to ensure they annoy enough so we would add reference texts to every property - documenting UI for best of user.
Best thing to add those references, instead of disabling warning.

**Comment by vkalpias** [comment]
This is now fixed.

**Comment by willeastcott** [comment]
You missed one:

![image](https://user-images.githubusercontent.com/697563/92046565-c11e4180-ed7a-11ea-8b76-37583cedc7d7.png)

**Comment by vkalpias** [comment]
Fixed
